VERSION 1.0 CLASS
BEGIN
  MultiUse = -1 
END
Attribute VB_Name = "clsClientInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public StatYear As Integrer
Public BrandName As String
Public typeBusiness As String
Public DatabaseClientNum As Integrer
Public DatabaseClientAndBrandNum As String
Public UniverseCode as Long
Public UniversCodeAndBrand as String
Public MregName as String
Public ExtMregName as String
Public RegNem as String
Public FLSMName as String
Public SecName as String
Public SrepName as String
Public ClientName as String
Public ChainName as String
Public ChainCode as Double
Public GeoCity as String
Public GeoReg as String
Public ClientTypeRus as String
Public ClientTypeEng as String
Public ClientTypeEngChort as String
Public ClientTypeEngChain as String
Public ClubStatus as String
Public EmotionStatus as String
Public CnqFullDate as Date
Public CnqYearDate as Date
Public CnqYearGA as String
Public CnqMonthNum as Integrer
Public CnqMonthNameRus as String
Public CnqMonthNameEng as String
Public Mag as String
Public MagPrice as String
Public MagPlace as String
Public WorkStatusNum as Integrer
Public WorkStatusName as String
Public LtmAvgCaVal as Double
Public LtmAvgCaName as String
Public LtmFrqOrders as String
Public ClientEvVal as Double
Public ClientEvName as String
Public ClientEcadCode as Integrer
Public MastersEducatedAllY as Integrer
Public MastersEducatedPY as Integrer
Public MastersEducatedTY as Integrer
Public HairdressersNum as Integrer
Public HairdressersWorkPlace as Integrer
Public PartnerName as Integrer
Public PartnerCode as Long











